import React from 'react';
import {TouchableOpacity, TouchableWithoutFeedback, View} from 'react-native';

import heartFilled from './heartFilled';
import heartBorder from './heartBorder';
import paw30 from './paw30';
import paw30Mixed from './paw30Mixed';
import private30 from './private30';
import public30 from './public30';
import cat38 from './cat38';
import dog38 from './dog38';
import cross from './cross';
import shelter46 from './shelter46';
import favoriteTagFilled from './favoriteTagFilled';
import paw46 from './paw46';
import setting46 from './setting46';
import heart46_filled from './heart46_filled';
import search48 from './search48';
import alarmBadger48 from './alarmBadger48';
import radioChecked38 from './radioChecked38';
import radioChecked48 from './radioChecked48';
import radioUnchecked38 from './radioUnchecked38';
import radioUnchecked48 from './radioUnchecked48';
import public48 from './public48';
import private48 from './private48';
import like48Border from './like48Border';
import like48Filled from './like48Filled';
import comment48Border from './comment48Border';
import paw48_YELL20 from './paw48_YELL20';
import paw48_Mixed from './paw48_Mixed';
import house48 from './house48';
import heart48_border from './heart48_border';
import paw48 from './paw48';
import telephone48 from './telephone48';
import check from './check';
import rectFilled from './rectFilled';
import rectBorder from './rectBorder';
import calendar48Filled from './calendar48Filled';
import share48Filled from './share48Filled';
import share48Border from './share48Border';
import favoriteTag48Border from './favoriteTag48Border';
import calendar48Border from './calendar48Border';
import person48 from './person48';
import phone48 from './phone48';
import textBalloon48 from './textBalloon48';
import male48 from './male48';
import female48 from './female48';
import videoPlay48 from './videoPlay48';
import imageList48 from './imageList48';
import cancel48 from './cancel48';
import cancel36 from './cancel36';
import bracket48 from './bracket48';
import starBorder from './starBorder';
import starFilled from './starFilled';
import meatball50h from './meatball50h';
import meatball50v from './meatball50v';
import hash50 from './hash50';
import heart52 from './heart52';
import eye52_apri10 from './eye52_apri10';
import eye52_gray20 from './eye52_gray20';
import location54_apri10 from './location54_apri10';
import location54_gray30 from './location54_gray30';
import camera54 from './camera54';
import pawBorder54 from './pawBorder54';
import location54Filled from './location54Filled';
import sirenRed58 from './sirenRed58';
import sirenWhite58 from './sirenWhite58';
import photo60 from './photo60';
import send60 from './send60';
import send60Big from './send60Big';
import lock60Border from './lock60Border';
import lock60Filled from './lock60Filled';
import dog62 from './dog62';
import cat62 from './cat62';
import rabbit62 from './rabbit62';
import paw62 from './paw62';
import paw62_mixed from './paw62_mixed';
import cancel62 from './cancel62';
import private62 from './private62';
import public62 from './public62';
import addItem64 from './addItem64';
import tag70 from './tag70';
import social_kakao72 from './social_kakao72';
import clip72 from './clip72';
import email72 from './email72';
import flashOff72 from './flashOff72';
import rotate72 from './rotate72';
import flashOn72 from './flashOn72';
import addItem92 from './addItem92';
import write94 from './write94';
import floatAddPet_126x92 from './floatAddPet_126x92';
import floatAddArticle126x92 from './floatAddArticle126x92';
import floatAddPet_128x68 from './floatAddPet_128x68';
import floatAddArticle128x68 from './floatAddArticle128x68';
import feedTabBorder from './feedTabBorder';
import animalSavingTabBorder from './animalSavingTabBorder';
import communityTabBorder from './communityTabBorder';
import myTabBorder from './myTabBorder';
import feedTabFilled from './feedTabFilled';
import animalSavingTabFilled from './animalSavingTabFilled';
import communityTabFilled from './communityTabFilled';
import myTabFilled from './myTabFilled';
import paw94x90 from './paw94x90';
import cameraLink from './cameraLink';
import hashLabel from './hashLabel';
import tagView from './tagView';
import tagEdit from './tagEdit';
import xMark from './xMark';
import addPet180 from './addPet180';
import urgent_write1 from './urgent_write1';
import urgent_write2 from './urgent_write2';
import leaflet from './leaflet';
import arrow_down from './arrow_down';
import arrow_up from './arrow_up';
import expiredDate from './expiredDate';
import nextMonthBtn from './nextMonthBtn';
import previousMonthBtn from './previousMonthBtn';
import expand_more from './expand_more';
import backarrow32 from './backarrow32';
import naverIcon from './naverIcon';
import kakaoIcon from './kakaoIcon';
import instagramIcon from './instagramIcon';
import facebookIcon from './facebookIcon';
import crossMark_filled from './crossMark_filled';
import childCommentLinker from './childCommentLinker';
import profiledefault1 from './profiledefault1';
import profiledefault2 from './profiledefault2';
import profiledefault3 from './profiledefault3';
import profiledefault4 from './profiledefault4';
import ready_for_updating from './ready_for_updating';
import mainLogo from './mainLogo';
import cross24 from './cross24';
import message94 from './message94';
import updateImg from './updateImg';
import posterSave from './posterSave';
import congratulation from './congratulation';
import newmeatball60 from './newMeatBall60';
import newmeatball60Filled from './newMeatBall60Filled';
import filter60Border from './filter60Border';
import filter60Filled from './filter60Filled';
import secureIcon40 from './secureIcon40';
import locationGray from './locationGray';
import animal_another from './animal_another';
import animal_another_off from './animal_another_off';
import animal_cat from './animal_cat';
import animal_cat_off from './animal_cat_off';
import animal_dog from './animal_dog';
import animal_dog_off from './animal_dog_off';
import rainbowBridge from './rainbowBridge';
import writeBoard from './writeBoard';
import loading from './loading';
import save54 from './save54';
import locationMarker from './locationMarker';
import currentLocation from './currentLocation';
import triangle from './triangle';
import photo44 from './photo44';
import alarmBadgerNotice48 from './alarmBadgerNotice48';
import articleIcon from './articleIcon';
import reviewIcon from './reviewIcon';
import emptyIcon from './emptyIcon';
import pawBorder54Gray from './pawBorder54Gray';
import checkFilled from './checkFilled';
import arrowMarkForCalendar from './arrowMarkForCalendar';
import hyhpen from './hyhpen';
import phoneIcon from './phoneIcon';
import blur from './blur';
import blur694 from './blur694';
import report from './report';
import report48 from './report48';
import crop72 from './crop72';
import like30 from './like30';
import comment30 from './comment30';

import crossNew92 from './crossNew92';
import shelter294 from './shelter294';
import blur246 from './blur246';
import arrow48 from './arrow48';

import arrow48_gray from './arrow48_gray';
import location54 from './location54';
import comment48 from './comment48';
import comment30_border from './comment30_border';

import paw46_border from './paw46_border';
import setting46Border from './setting46Border';
import circleMeatBall70 from './circleMeatBall70';
import home48Border from './home48Border';
import addItem68 from './addItem68';
import check64Filled from './check64Filled';
import edit46 from './edit46';
import infoIcon50 from './infoIcon50';
import feedIcon from './feedIcon';
import tagIcon from './tagIcon';
import communityIcon from './communityIcon';
import protectRequest from './protectRequest';
import addItem68Black from './addItem68Black';
import location40border from './location40border';
import location48border from './location48border';
import verticalBar from './verticalBar';

import DP from 'Root/config/dp';
import {APRI10, YELL20, GRAY20, GRAY30, GRAY10, BLACK, MAINBLACK} from 'Root/config/color';

const size30 = {width: 30 * DP, height: 30 * DP};
const size32 = {width: 32 * DP, height: 32 * DP};
const size36 = {width: 36 * DP, height: 36 * DP};
const size38 = {width: 38 * DP, height: 38 * DP};
const size40 = {width: 40 * DP, height: 40 * DP};
const size42 = {width: 42 * DP, height: 42 * DP};
const size46 = {width: 46 * DP, height: 46 * DP};
const size48 = {width: 48 * DP, height: 48 * DP};
const size50 = {width: 50 * DP, height: 50 * DP};
const size52 = {width: 52 * DP, height: 52 * DP};
const size54 = {width: 54 * DP, height: 54 * DP};
const size54x46 = {width: 54 * DP, height: 46 * DP};
const size58 = {width: 58 * DP, height: 58 * DP};
const size60 = {width: 60 * DP, height: 60 * DP};
const size62 = {width: 62 * DP, height: 64 * DP};
const size64 = {width: 64 * DP, height: 64 * DP};
const size68 = {width: 68 * DP, height: 68 * DP};
const size70 = {width: 70 * DP, height: 70 * DP};
const size72 = {width: 72 * DP, height: 72 * DP};
const size76 = {width: 72 * DP, height: 72 * DP};
const size80 = {width: 80 * DP, height: 80 * DP};
const size92 = {width: 92 * DP, height: 92 * DP};
const size94 = {width: 94 * DP, height: 94 * DP};
const size110 = {width: 110 * DP, height: 110 * DP};
const size126x92 = {width: 126 * DP, height: 92 * DP};
const size128x68 = {width: 128 * DP, height: 68 * DP};
const size206 = {width: 206 * DP, height: 206 * DP};
const defaultProfileImg = {width: 294 * DP, height: 294 * DP};
const profileDefaultImg_194 = {width: 194 * DP, height: 194 * DP};

const makeSvg = (component, style, color) => {
	if (!color) {
		return props =>
			props.onPress
				? React.createElement(TouchableOpacity, {...props}, React.createElement(component, {...props, ...style}))
				: React.createElement(component, {...props, ...style});
	}
	return props => {
		return props.onPress
			? React.createElement(TouchableOpacity, {...props}, React.createElement(component, {...style, fill: color}))
			: React.createElement(component, {...style, fill: color});
	};
};

export const UpdateImg = makeSvg(updateImg, size206);
export const ProfileDefaultImg1 = makeSvg(profiledefault1, defaultProfileImg, '');
export const ProfileDefaultImg2 = makeSvg(profiledefault2, defaultProfileImg, '');
export const ProfileDefaultImg3 = makeSvg(profiledefault3, defaultProfileImg, '');
export const ProfileDefaultImg1_194 = makeSvg(profiledefault1, profileDefaultImg_194, '');
export const ProfileDefaultImg2_194 = makeSvg(profiledefault2, profileDefaultImg_194, '');
export const ProfileDefaultImg3_194 = makeSvg(profiledefault3, profileDefaultImg_194, '');
export const ProfileDefaultImg1_70 = makeSvg(profiledefault1, size70, '');
export const ProfileDefaultImg = props => {
	return React.createElement(View, {...props}, React.createElement(profiledefault1, {...props.size, fill: props.color}));
};

export const Heart30_Filled = makeSvg(heartFilled, size30, APRI10);
export const Heart30_Border = makeSvg(heartBorder, size30, APRI10);
export const Paw30_APRI10 = makeSvg(paw30, size30, APRI10);
export const Paw30_YELL20 = makeSvg(paw30, size30, YELL20);
export const Paw30_Mixed = makeSvg(paw30Mixed, size30, '');
export const Private30 = makeSvg(private30, size30, '');
export const Public30 = makeSvg(public30, size30, '');
export const BackArrow32 = makeSvg(backarrow32, size32, BLACK);
export const Cat38 = makeSvg(cat38, size38);
export const Dog38 = makeSvg(dog38, size38);
export const Cross46 = makeSvg(cross, size46, GRAY10);
export const Shelter46 = makeSvg(shelter46, size46);
export const FavoriteTag46_Filled = makeSvg(favoriteTagFilled, size46, APRI10);
export const Paw46 = makeSvg(paw46, size46);
export const Setting46 = makeSvg(setting46, size46);
export const Heart46_Filled = makeSvg(heart46_filled, size46); //Added 21.10.27
export const Search48 = makeSvg(search48, size48, GRAY10);
export const Search48_BLACK = makeSvg(search48, size48, BLACK);
export const AlarmBadger48 = makeSvg(alarmBadger48, size48);
export const RadioChecked38 = makeSvg(radioChecked48, size48);
export const RadioChecked48 = makeSvg(radioChecked48, size48);
export const RadioUnchecked38 = makeSvg(radioUnchecked48, size48, GRAY30);
export const RadioUnchecked48 = makeSvg(radioUnchecked48, size48);
export const Public48 = makeSvg(public48, size48);
export const Private48 = makeSvg(private48, size48);
export const Like48_Border = makeSvg(like48Border, size48);
export const Like48_Filled = makeSvg(like48Filled, size48);
export const Like30_Border = makeSvg(like48Border, size30);
export const Like30_Filled = makeSvg(like48Filled, size30);
export const Comment48_Border = makeSvg(comment48Border, size48);
export const Heart48_Filled = makeSvg(heartFilled, size48, APRI10);
export const Heart48_Border = makeSvg(heart48_border, size48); //Added 21.10.27
export const Paw48_YELL20 = makeSvg(paw48_YELL20, size48, YELL20);
export const Paw48_Mixed = makeSvg(paw48_Mixed, size48);
export const House48 = makeSvg(house48, size48);
export const Paw48_APRI10 = makeSvg(paw48, size48);
export const Telephone48 = makeSvg(telephone48, size48);
export const Check42 = makeSvg(check, size42);
export const Check48 = makeSvg(check, size48);
export const Rect48_APRI10 = makeSvg(rectFilled, size48, APRI10);
export const Rect48_GRAY30 = makeSvg(rectFilled, size48, GRAY30);
export const Rect48_Border = makeSvg(rectBorder, size48);
export const Calendar48_Filled = makeSvg(calendar48Filled, size48);
export const Share48_Filled = makeSvg(share48Filled, size48);
export const Share48_Border = makeSvg(share48Border, size48);
export const FavoriteTag48_Filled = makeSvg(favoriteTagFilled, size48, APRI10);
export const FavoriteTag48_Border = makeSvg(favoriteTag48Border, size48, GRAY10);
export const Calendar48_Border = makeSvg(calendar48Border, size48);
export const Cross48 = makeSvg(cross, size48);
export const Person48 = makeSvg(person48, size48);
export const Phone48 = makeSvg(phone48, size48);
export const TextBalloon48 = makeSvg(textBalloon48, size48);
export const Male48 = makeSvg(male48, size48);
export const Female48 = makeSvg(female48, size48);
export const VideoPlay48 = makeSvg(videoPlay48, size48);
export const ImageList48 = makeSvg(imageList48, size48);
export const Cancel48 = makeSvg(cancel48, size48);
export const Cancel36 = makeSvg(cancel36, size36);
export const Bracket48 = makeSvg(bracket48, size48);
export const Star50_Border = makeSvg(starBorder, size50);
export const Star50_Filled = makeSvg(starFilled, size50);
export const Meatball50_GRAY20_Horizontal = makeSvg(meatball50h, size50, GRAY20);
export const Meatball50_APRI10_Horizontal = makeSvg(meatball50h, size50, APRI10);
export const Meatball50_GRAY20_Vertical = makeSvg(meatball50v, size50, GRAY20);
export const Meatball50_APRI10_Vertical = makeSvg(meatball50v, size50, APRI10);
export const Hash50 = makeSvg(hash50, size50);
export const Rect50_Border = makeSvg(rectBorder, size50);
export const Rect42_Border = makeSvg(rectBorder, size42);
export const Check50 = makeSvg(check, size50);
export const Heart52_Border = makeSvg(heartBorder, size52, APRI10);
export const Heart52 = makeSvg(heart52, size52);
export const Eye52_APRI10 = makeSvg(eye52_apri10, size52, APRI10);
export const Eye52_GRAY20 = makeSvg(eye52_gray20, size52, GRAY20);
export const Cross52 = makeSvg(cross, size52);
export const Location54_APRI10 = makeSvg(location54_apri10, size54);
export const Location54 = makeSvg(location54, size54);
export const Location54_GRAY30 = makeSvg(location54_gray30, size54);
export const Location54_Filled = makeSvg(location54Filled, size54);
export const Camera54 = makeSvg(camera54, size54);
export const Paw54_Border = makeSvg(pawBorder54, size54);
export const Paw54_Gray = makeSvg(pawBorder54Gray, size54);
export const Siren58_Red = makeSvg(sirenRed58, size58);
export const Siren58_White = makeSvg(sirenWhite58, size58);
export const Star60_Border = makeSvg(starBorder, size60);
export const Star60_Filled = makeSvg(starFilled, size60);
export const Photo60 = makeSvg(photo60, size60);
export const Send60 = makeSvg(send60, size60);
export const Send60_Big = makeSvg(send60Big, size60);
export const Lock60_Border = makeSvg(lock60Border, size60);
export const Lock60_Filled = makeSvg(lock60Filled, size60);
export const Dog62 = makeSvg(dog62, size62);
export const Cat62 = makeSvg(cat62, size62);
export const Rabbit62 = makeSvg(rabbit62, size62);
export const Paw62_APRI10 = makeSvg(paw62, size62, APRI10);
export const Paw62_YELL20 = makeSvg(paw62, size62, YELL20);
export const Paw62_Mixed = makeSvg(paw62_mixed, size62);
export const Cancel62 = makeSvg(cancel62, size62);
export const Private62 = makeSvg(private62, size62);
export const Public62 = makeSvg(public62, size62);
export const AddItem64 = makeSvg(addItem64, size64);
export const Tag70 = makeSvg(tag70, size70);
export const SocialKakao72 = makeSvg(social_kakao72, size72);
export const Clip72 = makeSvg(clip72, size72);
export const Email72 = makeSvg(email72, size72);
export const FlashOff72 = makeSvg(flashOff72, size72);
export const Rotate72 = makeSvg(rotate72, size72);
export const FlashOn72 = makeSvg(flashOn72, size72);
export const AddItem92 = makeSvg(addItem92, size92);
export const Write94 = makeSvg(write94, size94);
export const FloatAddPet_126x92 = makeSvg(floatAddPet_126x92, size126x92);
export const FloatAddPet_128x68 = makeSvg(floatAddPet_128x68, {width: 120 * DP, height: 68 * DP});
export const FloatAddArticle_126x92 = makeSvg(floatAddArticle126x92, size126x92);
export const FloatAddArticle_128x68 = makeSvg(floatAddArticle128x68, {width: 120 * DP, height: 68 * DP});
export const FeedTabBorder = makeSvg(feedTabBorder, {width: 66 * DP, height: 48 * DP});
export const AnimalSavingTabBorder = makeSvg(animalSavingTabBorder, {width: 54 * DP, height: 46 * DP}, GRAY20);
export const CommunityTabBorder = makeSvg(communityTabBorder, {width: 54 * DP, height: 48 * DP}, GRAY20);
export const MyTabBorder = makeSvg(myTabBorder, {width: 50 * DP, height: 48 * DP});
export const FeedTabFilled = makeSvg(feedTabFilled, {width: 66 * DP, height: 48 * DP}, BLACK);
export const AnimalSavingTabFilled = makeSvg(animalSavingTabFilled, {width: 54 * DP, height: 46 * DP}, BLACK);
export const CommunityTabFilled = makeSvg(communityTabFilled, {width: 54 * DP, height: 48 * DP}, BLACK);
export const MyTabFilled = makeSvg(myTabFilled, {width: 50 * DP, height: 48 * DP});

// Added for molecules
export const Paw94x90 = makeSvg(paw94x90, {width: 94 * DP, height: 90 * DP});
export const CameraLinkIcon = makeSvg(cameraLink, {width: 86 * DP, height: 70 * DP});
export const HashLabel46 = makeSvg(hashLabel, size46);
export const HashLabel94 = makeSvg(hashLabel, size94);
export const HashLabel76 = makeSvg(hashLabel, size76);
export const HashLabel70 = makeSvg(hashLabel, size70);
export const HashLabel60 = makeSvg(hashLabel, size60);
export const Tag_View = makeSvg(tagView, {width: 110 * DP, height: 52 * DP});
export const Tag_Edit = makeSvg(tagEdit, {width: 170 * DP, height: 52 * DP});
export const X_Mark = makeSvg(xMark, size48);
export const Add_Pet = makeSvg(addPet180, {width: 180 * DP, height: 180 * DP});
export const Add_Volunteer = makeSvg(addPet180, {width: 94 * DP, height: 94 * DP});
export const Urgent_Write1 = makeSvg(urgent_write1, {width: 98 * DP, height: 86 * DP});
export const Urgent_Write2 = makeSvg(urgent_write2, {width: 98 * DP, height: 86 * DP});
export const Leaflet = makeSvg(leaflet, {width: 118 * DP, height: 110 * DP});
export const Arrow_Down_White = makeSvg(arrow_down, size48, 'white');
export const Arrow_Down_APRI10 = makeSvg(arrow_down, size48, APRI10);
export const Arrow_Down_GRAY30 = makeSvg(arrow_down, size48, GRAY30);
export const Arrow_Down_GRAY10 = makeSvg(arrow_down, size48, GRAY10);
export const Arrow_Down_GRAY20 = makeSvg(arrow_down, size48, GRAY20);
export const Arrow_Down_BLACK = makeSvg(arrow_down, size48, BLACK);
export const Arrow_Up_APRI10 = makeSvg(arrow_up, size48, APRI10);
export const Arrow_Up_GRAY30 = makeSvg(arrow_up, size48, GRAY30);
export const Arrow_Up_GRAY10 = makeSvg(arrow_up, size48, GRAY10);
export const Arrow_Up_GRAY20 = makeSvg(arrow_up, size48, GRAY20);
export const Arrow_Up_White = makeSvg(arrow_up, size48, 'white');
export const Arrow_UP_BLACK = makeSvg(arrow_up, size48, BLACK);
export const Mercy_Killing = makeSvg(expiredDate, {width: 134 * DP, height: 27 * DP});
export const NextMark = makeSvg(nextMonthBtn, {width: 12 * DP, height: 20 * DP}, GRAY10);
export const NextMark48 = makeSvg(nextMonthBtn, {width: 48 * DP, height: 48 * DP}, GRAY10);

export const NextMark_APRI = makeSvg(nextMonthBtn, {width: 12 * DP, height: 20 * DP}, APRI10);
export const PreviousMonthBtn = makeSvg(previousMonthBtn, {width: 12 * DP, height: 20 * DP});
export const VideoPlay_Feed = makeSvg(videoPlay48, size94);

export const Naver_Icon = makeSvg(naverIcon, size80);
export const Kakao_Icon = makeSvg(kakaoIcon, size80);
export const Instagram_Icon = makeSvg(instagramIcon, size80);
export const Facebook_Icon = makeSvg(facebookIcon, size80);
export const CrossMark_Filled = makeSvg(crossMark_filled, size50);
export const ChildCommentLinker = makeSvg(childCommentLinker, {width: 14 * DP, height: 14 * DP});
export const Ready_for_updating = makeSvg(ready_for_updating, {width: 382 * DP, height: 382 * DP});
export const Cross24_Filled = makeSvg(cross24, {width: 24 * DP, height: 24 * DP}, GRAY10);
export const Cross24_White = makeSvg(cross24, {width: 24 * DP, height: 24 * DP}, 'white');
export const PosterSave = makeSvg(posterSave, size54x46);
export const Message94 = makeSvg(message94, size94);
export const MainLogo = makeSvg(mainLogo, {width: 122 * DP, height: 90 * DP});
export const Congratulation = makeSvg(congratulation, {width: 124 * DP, height: 110 * DP});
export const NewMeatBall60 = makeSvg(newmeatball60, size60);
export const NewMeatBall60Filled = makeSvg(newmeatball60Filled, size60);
export const Filter60Border = makeSvg(filter60Border, size60);
export const Filter60Filled = makeSvg(filter60Filled, size60);
export const SecureIcon40 = makeSvg(secureIcon40, size40);
export const LocationGray = makeSvg(locationGray, {width: 40 * DP, height: 40 * DP});
export const Animal_another = makeSvg(animal_another, {width: 42 * DP, height: 30 * DP});
export const Animal_another_off = makeSvg(animal_another_off, {width: 42 * DP, height: 30 * DP});
export const Animal_cat = makeSvg(animal_cat, {width: 42 * DP, height: 30 * DP});
export const Animal_cat_off = makeSvg(animal_cat_off, {width: 42 * DP, height: 30 * DP});
export const Animal_dog = makeSvg(animal_dog_off, {width: 42 * DP, height: 30 * DP});
export const Animal_dog_off = makeSvg(animal_dog, {width: 42 * DP, height: 30 * DP});
export const RainbowBridge = makeSvg(rainbowBridge, {width: 132 * DP, height: 170 * DP});
export const RainbowBridge_226 = makeSvg(rainbowBridge, {width: 66 * DP, height: 86 * DP});
export const WriteBoard = makeSvg(writeBoard, size94);
export const LoadingImg = makeSvg(loading, {width: 150 * DP, height: 150 * DP});
export const Save54 = makeSvg(save54, {width: 54 * DP, height: 54 * DP});
export const LocationMarker = makeSvg(locationMarker, {width: 80 * DP, height: 80 * DP});
export const CurrentLocation = makeSvg(currentLocation, {width: 100 * DP, height: 100 * DP});
export const Triangle = makeSvg(triangle, {width: 26 * DP, height: 18 * DP});
export const Photo44 = makeSvg(photo44, {width: 44 * DP, height: 35 * DP});
export const AlarmBadgerNotice = makeSvg(alarmBadgerNotice48, size48);
export const ArticleIcon = makeSvg(articleIcon, {width: 46 * DP, height: 54 * DP});
export const ReviewIcon = makeSvg(reviewIcon, {width: 46 * DP, height: 54 * DP});
export const EmptyIcon = makeSvg(emptyIcon, {width: 210 * DP, height: 218 * DP});
export const CheckFilled = makeSvg(checkFilled, size52);
export const ArrowMarkForCalendar = makeSvg(arrowMarkForCalendar, {width: 22 * DP, height: 22 * DP});
export const Location42_APRI10 = makeSvg(location54_apri10, {width: 42 * DP, height: 42 * DP});
export const Hyhpen = makeSvg(hyhpen, {width: 26 * DP, height: 2 * DP});
export const PhoneIcon = makeSvg(phoneIcon, {width: 32 * DP, height: 32 * DP});
export const Blur = makeSvg(blur, {width: 226 * DP, height: 226 * DP});
export const Blur694 = makeSvg(blur694, {width: 694 * DP, height: 694 * DP});
export const Blur246 = makeSvg(blur246, {width: 251 * DP, height: 251 * DP});
export const Report30 = makeSvg(report, size30);
export const Report48 = makeSvg(report48, size48);
export const Crop72 = makeSvg(crop72, {width: 72 * DP, height: 72 * DP});
export const Like30 = makeSvg(like30, size30);
export const Comment30 = makeSvg(comment30, size30);
export const Comment30_Border = makeSvg(comment30_border, size30);
export const ProfileDefaultImg4 = makeSvg(profiledefault4, {width: 294 * DP, height: 294 * DP});
export const CrossNew92 = makeSvg(crossNew92, size92);
export const Shelter294 = makeSvg(shelter294, {width: 294 * DP, height: 294 * DP});
export const Arrow48 = makeSvg(arrow48, size48);

export const Comment48 = makeSvg(comment48, size48);
export const Arrow48_GRAY = makeSvg(arrow48_gray, size48);

export const Paw46_border = makeSvg(paw46_border, size46, MAINBLACK);
export const Setting46_border = makeSvg(setting46Border, size46, MAINBLACK);
export const CircleMeatBall70 = makeSvg(circleMeatBall70, size70);
export const Home48Border = makeSvg(home48Border, size48, MAINBLACK);
export const AddItem68 = makeSvg(addItem68, size68, APRI10);
export const AddItem68Black = makeSvg(addItem68Black, size68, MAINBLACK);
export const Check64Filled = makeSvg(check64Filled, size64, APRI10);
export const Edit46 = makeSvg(edit46, size46, APRI10);
export const InfoIcon50 = makeSvg(infoIcon50, size50);
export const FeedIcon = makeSvg(feedIcon, size54, MAINBLACK);
export const FeedIcon_GRAY = makeSvg(feedIcon, size54, GRAY20);
export const TagIcon = makeSvg(tagIcon, size54, MAINBLACK);
export const TagIcon_GRAY = makeSvg(tagIcon, size54, GRAY20);
export const CommunityIcon = makeSvg(communityIcon, size54, MAINBLACK);
export const CommunityIcon_GRAY = makeSvg(communityIcon, size54, GRAY20);
export const ProtectRequestIcon = makeSvg(protectRequest, size54, MAINBLACK);
export const ProtectRequestIcon_GRAY = makeSvg(protectRequest, size54, GRAY20);
export const Location40Border = makeSvg(location40border,size40,'#1A1311');
export const Location48Border = makeSvg(location48border,size48,'#1A1311');

export const VerticalBar = makeSvg(verticalBar, {width: 2 * DP, height: 32 * DP}, '#767676');
