require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
rn_maps_path = '../node_modules/react-native-maps' # 22.03.15 구글 맵스 활용을 위한 추가 (KSW)

platform :ios, '11.0'

target 'anilog' do

  config = use_native_modules!
  permissions_path = '../node_modules/react-native-permissions/ios' # ios환경에서 gps location right detecting을 위한 추가
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
  pod 'Permission-LocationAccuracy', :path => "#{permissions_path}/LocationAccuracy" # ios환경에서 gps location right detecting을 위한 추가
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways" # ios환경에서 gps location right detecting을 위한 추가
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse" # ios환경에서 gps location right detecting을 위한 추가
  # pod 'react-native-google-maps', :path => rn_maps_path 
  # pod 'GoogleMaps' 
  # pod 'Google-Maps-iOS-Utils'

  # pod 'react-native-google-maps', :path => rn_maps_path # 22.03.15 구글 맵스 활용을 위한 추가 (KSW)
  # pod 'react-native-maps', :path => rn_maps_path # 22.03.15 구글 맵스 활용을 위한 추가 (KSW)
  pod 'SDWebImage', :modular_headers => true
  pod 'SDWebImagePhotosPlugin'
  
  pod 'VideoEditorSDK'
  target 'anilogTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!()

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
